OCA/ansible-odoo

README.md, defaults/main.yml, tasks/main.yml
Note: a checkout will always occured on the first playbook run, even with 'odoo_repo_update: False' (fix issue #8).
=> [IMP] New option 'odoo_repo_update' (default to True) to have more control on the repository checkout

tasks/install.yml
Ansible seems to ignore  when  is not explicitly set to , which may cause the repository to be cloned as the user .
=> Missing sudo attribute in git/hg cloning

defaults/main.yml, tasks/main.yml, tasks/wkhtmltox.yml, vars/main.yml
The option ``odoo_wkhtmltox_version`` allows to choose the version to install, and the ``odoo_wkhtmltox_urls`` variable contains a list of URLs on which the download will be attempted (fix #5).
As ``wkhtmltopdf`` is installed from upstream Debian packages, it only works from the ``0.12.1`` version.
@clonedagain : have you any feedback on this before a merge?
=> [IMP] Installation of the wkhtmltox tool.

README.md, defaults/main.yml, tasks/main.yml, tasks/reportlab.yml
Fixes https://github.com/osiell/ansible-odoo/issues/18
As per odoo/odoo#3234, we have to install a bunch of extra fonts for the barcodes to be printed on the standard reports.
The fonts must be downloaded from the upstream reportlab website directly.
We install the fonts to `/home/{{odoo_user}}/fonts` as suggested by @sebalix.
=> Install the ReportLab fonts for barcodes

.travis.yml, README.md, defaults/main.yml, files/bootstrap.py, meta/main.yml, tasks/install.yml, tasks/install_buildout.yml, tasks/install_npm.yml, tasks/install_standard.yml, tasks/main.yml, tasks/postgresql_local.yml, tasks/postgresql_remote.yml, tasks/service.yml, templates/odoo-buildout.init, tests/run.sh, tests/test.yml, tests/test_buildout.yml, tests/test_buildout_changed.yml, tests/test_standard.yml, tests/test_standard_changed.yml, vars/Debian-7.yml, vars/Odoo-9.yml, vars/main.yml
New option `odoo_install_type` which takes the value `standard` (default) or `buildout`.
The following options are also available to tune the `buildout` installation:
```yaml
odoo_buildout_venv_path: "{{ odoo_workdir }}/sandbox"
odoo_buildout_bootstrap_path: "{{ odoo_workdir }}/bootstrap.py"
odoo_buildout_bin_path: "{{ odoo_workdir }}/bin/buildout"
odoo_buildout_config_path: "{{ odoo_workdir }}/buildout.cfg"
odoo_buildout_odoo_bin_path: "{{ odoo_workdir }}/bin/start_odoo"
```
=> [IMP] Add the 'buildout' install type (anybox.recipe.odoo integration)

vars/Debian-7.yml, vars/Ubuntu-12.yml, vars/Ubuntu-14.yml, vars/Ubuntu.yml
These packages differs between distributions and releases. (#39 improvements)
=> [FIX] buildout - Pillow requires some development libraries to support some image formats

templates/odoo-buildout.init
by passing its value to the --load command line option.
=> [IMP] buildout - Update the init script to support 'server_wide_modules' configuration option

defaults/main.yml
=> [FIX] Set 'odoo_user_sshkeys' with an empty string

tasks/postgresql.yml
Delegating to the current ansible_host works only if the host matches the inventory name and default ssh port is used. Using the inventory name instead will let Ansible do the translation.
For example, when using Vagrant we'll have ansible_host=127.0.0.1 and use a random ssh port, wherease ansible_host works as expected.
=> Delegate to the inventory host

vars/Ubuntu-16.yml
There's not Xenial package for wkhtmltox 0.12.1, but the trusty one should work just fine
Fixes #45
=> Add Xenial specifics

tests/travis_lxd/create_container.sh, tests/travis_lxd/fix_debian_jessie.sh, tests/travis_lxd/install.sh, tests/travis_lxd/lxd-debconf
Official LXD PPA deprecated/removed and snap does not work on Trusty.
Some LXD features are missing in 2.0:
- ``lxc network``: the bridge configuration is now done through ``debconf``
- ``lxc file``: the `ansible-odoo` project is now copied directly inside the `rootfs` of the container (hackish but functional)
=> [FIX] .travis.yml: Install an old release (2.0) of LXD from trusty-backports

README.md, defaults/main.yml, tasks/install_pip.yml, templates/odoo-10.0-pip-requirements.txt, templates/odoo-11.0-pip-requirements.txt, templates/odoo-8.0-pip-requirements.txt, templates/odoo-9.0-pip-requirements.txt, tests/run.sh, vars/Debian-9_Odoo-10.yml, vars/Debian-9_Odoo-8.yml, vars/Debian-9_Odoo-9.yml
@jbeficent unfortunately Travis tests were broken (and since a long time!).
I also fixed the ``odoo_pip_odoo_bin_path`` variable to handle Odoo < 10 (./odoo.py) and Odoo >= 10 (./odoo) + the ownership of files generated through pip.
Your review is welcome.
=> Fix pip install + Others things

defaults/main.yml, tasks/wkhtmltox.yml, tests/run.sh, vars/Debian-8_Odoo-10.yml, vars/Debian-8_Odoo-8.yml, vars/Debian-8_Odoo-9.yml, vars/Debian-9_Odoo-10.yml, vars/Debian-9_Odoo-11.yml, vars/Debian-9_Odoo-8.yml, vars/Debian-9_Odoo-9.yml, vars/Ubuntu-14_Odoo-10.yml, vars/Ubuntu-14_Odoo-8.yml, vars/Ubuntu-14_Odoo-9.yml, vars/Ubuntu-16_Odoo-10.yml, vars/Ubuntu-16_Odoo-11.yml, vars/Ubuntu-16_Odoo-8.yml, vars/Ubuntu-16_Odoo-9.yml, vars/main.yml
from the generic linux package (.tar.gz) on Debian Stretch.
Still needs some local tests to check if Odoo 8 + wkhtmltopdf 0.12.4 works well.
=> [IMP] wkhtmltox: handle the installation of wkhtmltox 0.12.4

defaults/main.yml, tasks/install.yml, templates/odoo-pip.init, templates/odoo-pip.service, templates/odoo-standard.service
I am adding some fixes as I am getting more on hands with it. Specifically to the pip install.
But I also found that we need a default path for logging of odoo. Otherwise one can forget to add it to the playbook and the logs are then lost.
=> Fixes mostly to pip install

tasks/reportlab.yml, vars/main.yml
At the moment, optional libs are placed in /root as mentioned in #19.
This pr implements the modification and place those libraries into /opt instead of /root.
=> [IMP] Move optional libraries in /opt instead of /root.

tasks/install.yml
=> [FIX] Wait for the project to be cloned before creating the Odoo data directory

handlers/main.yml, tasks/service.yml
Fixes #77 .
Please allow me to suggest this change to ensure that systemd gets reloaded after there was a change in the odoo.service file that defines Odoo as a systemd service. Otherwise, changes to that file won't be recognized.
Please test!
=> Handling systemd restart

vars/Debian-8_Odoo-10.yml, vars/Debian-8_Odoo-8.yml, vars/Debian-8_Odoo-9.yml, vars/Ubuntu-14_Odoo-10.yml, vars/Ubuntu-14_Odoo-8.yml, vars/Ubuntu-14_Odoo-9.yml, vars/Ubuntu-16_Odoo-10.yml, vars/Ubuntu-16_Odoo-11.yml, vars/Ubuntu-16_Odoo-8.yml, vars/Ubuntu-16_Odoo-9.yml
Problem:
The task "Install Odoo dependencies (PyPi)" was installing `pip==9.0.1` as specified in the `odoo_pip_dependencies` while the next task "Install Odoo from pip external requirements file" force the installation of `pip` 9.0.2 which has been released a couple a days (https://pypi.python.org/pypi/pip/9.0.2) resulting in a "changed" state.
All Odoo releases seems affected on Debian Jessie, Ubuntu Trusty and Ubuntu Xenial (not Debian Stretch which already provides `pip>=9`).
Errors available on Travis: https://travis-ci.org/OCA/ansible-odoo/builds/355308939
Fix:
Install `pip>=9.0.1` (the 9.0.2 should be installed in new environnements, while the existing ones will be upgraded to `pip==9.0.2` when executing the "Install Odoo from pip external requirements file" task.
ping @jbeficent
=> [FIX] pip install type: require 'pip >= 9.0.1' to not trigger 'changed' event on each playbook execution

tasks/install_pip.yml
This option is required to ensure that the latest OCA modules are always installed. Otherwise you get errors when a new version of an OCA module is released.
For example, when you specify in the requirements file this package:
odoo11-addon-auth_brute_force
This will install in fact the latest package from https://wheelhouse.odoo-community.org/oca-simple/odoo10-addon-auth-brute-force/
The next time you run ansible, if a new version of the module has been released, you will want to install it. 
The current --upgrade option is giving errors because it is still expecting older versions of packages. 
This will increase the time to run the playbook, but it is way more reliable IMHO.
Perhaps @sbidoul knows better.
=> add option to force reinstall pip packages in pip install method

templates/odoo-10.0.init, templates/odoo-8.0.init, templates/odoo-9.0.init, templates/odoo-buildout.init, templates/odoo-buildout.service, templates/odoo-pip.init, templates/odoo-pip.service, templates/odoo-standard.service
Fixing `iteritems()` removal in Python 3 replacing by `items()` and `list` Jinja filter.
See more:
https://docs.ansible.com/ansible/2.6/user_guide/playbooks_python_version.html#pb-py-compat-dict-views
=> [FIX] templates Python 3 compat
